name: resource_state
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/boginni/resource_state

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

