name: resource_state
description: A expansion to value notifier to handle async operations
version: 1.1.0
repository: https://github.com/boginni/resource_state

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

